services:
  db:
    image: postgres:16
    container_name: spotify_postgres
    environment:
      POSTGRES_DB: spotify_analytics
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5434:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d spotify_analytics"]
      interval: 5s
      timeout: 5s
      retries: 5

  api:
    build: .
    container_name: spotify_api
    ports:
      - "8001:8000"
    depends_on:
      db:
        condition: service_healthy
    environment:
      DATABASE_URL: postgresql://postgres:postgres@db:5432/spotify_analytics

volumes:
  postgres_data: